//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AlreadySample 的本地化字符串。
        /// </summary>
        internal static string AlreadySample {
            get {
                return ResourceManager.GetString("AlreadySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /RDS;component/Apps/Languages/zh-CN.xaml 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseConnectionString 的本地化字符串。
        /// </summary>
        internal static string DatabaseConnectionString {
            get {
                return ResourceManager.GetString("DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /RDS;component/Apps/Languages/en-US.xaml 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message1 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message1 {
            get {
                return ResourceManager.GetString("FinalView_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message2 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message2 {
            get {
                return ResourceManager.GetString("FinalView_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMdd 的本地化字符串。
        /// </summary>
        internal static string LisFileNameFormat {
            get {
                return ResourceManager.GetString("LisFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LisFilesPath 的本地化字符串。
        /// </summary>
        internal static string LisFilesPath {
            get {
                return ResourceManager.GetString("LisFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSample 的本地化字符串。
        /// </summary>
        internal static string NotSample {
            get {
                return ResourceManager.GetString("NotSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_About 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_About {
            get {
                return ResourceManager.GetString("PopupWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Administrators 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Administrators {
            get {
                return ResourceManager.GetString("PopupWindow_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_MessageBox 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_MessageBox {
            get {
                return ResourceManager.GetString("PopupWindow_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrepareSample 的本地化字符串。
        /// </summary>
        internal static string PrepareSample {
            get {
                return ResourceManager.GetString("PrepareSample", resourceCulture);
            }
        }
    }
}
